"""
all_channels.py

Swagger Generated All Channels Model

This class is autogenerated by Swagger.
"""
from __future__ import absolute_import
from swagger_server.models.base_model_ import Model
from swagger_server import util


class AllChannels(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """AllChannels - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'AllChannels':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AllChannels of this AllChannels.  # noqa: E501
        :rtype: AllChannels
        """
        return util.deserialize_model(dikt, cls)
