"""
attatchment.py

SQLCodegen Generated Database Table: Attatchment

This class is autogenerated by SQLCodegen, for use with SQLAlchemy
"""
from sqlalchemy import Column, ForeignKey, String
from sqlalchemy.dialects.mysql import INTEGER
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base
from swagger_server.__main__ import database

Base = declarative_base()
metadata = Base.metadata


class Attatchment(database.Model):
    __tablename__ = 'attatchment'

    attatchment_id = Column(INTEGER(), primary_key=True)
    file_name = Column(String(32), nullable=False)
    message_id = Column(ForeignKey('message.message_id'), nullable=False, index=True)
    file_size = Column(INTEGER(), nullable=False)
    file_url = Column(String(255), nullable=False)

    message = relationship('Message')
