"""
channel.py

SQLCodegen Generated Database Table: Channel

This class is autogenerated by SQLCodegen, for use with SQLAlchemy
"""
from swagger_server.__main__ import database
from sqlalchemy import insert


class Channel(database.Model):
    __tablename__ = 'channel'

    channel_id = database.Column(database.INTEGER(), primary_key=True)
    channel_name = database.Column(database.String(32), nullable=False)
    user_id = database.Column(database.ForeignKey('user.user_id'), nullable=False, index=True)
    channel_capacity = database.Column(database.INTEGER(), nullable=False)
    channel_type = database.Column(database.Enum('TEXT', 'VOICE', 'DM'), nullable=False)
    channel_position = database.Column(database.INTEGER(), nullable=False)

    user = database.relationship('User')

    def insert_into_db(self, id, chnl_name, usr_id, chnl_cap, chnl_type, chnl_pos):
        ins = self.__tablename__.insert().vales(
            id, chnl_name,
            usr_id, chnl_cap,
            chnl_type, chnl_pos)
