"""
channel_controller.py

OpenAPI Generated Controller: Channel

This class is autogenerated by OpenAPI, for use with SQLAlchemy.
https://github.com/OpenAPITools/openapi-generator
"""
import connexion
from sqlalchemy.exc import SQLAlchemyError
from swagger_server.models.all_channels import AllChannels
from swagger_server.models.channel import Channel  # Swagger model
from ..models.db_models.channel import Channel as dbChannel  # Database model
from ..__main__ import database


def add_channel(body=None):  # noqa: E501
    """Channel has been created

    Channel has been created # noqa: E501

    SQL Query:
    insert into channel(channel_name, user_id, channel_capacity, channel_type, channel_position)
    values (String, int, int, enum, int);

    :param session:
    :param body: The Channel to be create
    :type body: dict | bytes

    :rtype: None
    """
    try:
        if connexion.request.is_json:
            print(connexion.request.get_json())
            # Get body from request
            body = Channel.from_dict(connexion.request.get_json())  # noqa: E501
            # body = connexion.request.get_json()

            print(body)  # Print for verification

            # TODO: Want to look at checking for existing channel
            # De-serialise data into fresh object

            channel = dbChannel(channel_id=body.id, channel_name=body.name,
                                user_id=body.user_id, channel_capacity=body.capacity,
                                channel_type=body.type, channel_position=body.position)
            print(channel)  # Display for verification

            database.session.add(channel)
            database.session.commit()

            # chnl = Channel.from_dict(new_channel)
            # database.session.add(chnl)  # insert code
            # print("chnl", chnl)

        return 200
    except SQLAlchemyError as e:
        error = str(e.__dict__['orig'])
        return error


def delete_channel_by_id(id):  # noqa: E501
    """Deletes an existing channel

    Deletes an existing channel # noqa: E501

    :param id: The channel ID
    :type id: int

    :rtype: None
    """
    return 'do some magic!'


def get_all_channels():  # noqa: E501
    """Returns all channels

    Returns all channels in a server # noqa: E501


    :rtype: AllChannels
    """
    try:
        # Query DB
        query = dbChannel.query.all()
        response = []
        # Loop through query results and build channel objects for response
        for channel in query:
            c = Channel()
            c.id = channel.channel_id
            c.name = channel.channel_name
            c.capacity = channel.channel_capacity
            c.type = channel.channel_type
            c.position = channel.channel_position
            response.append(c)

        # Return all channels
        res = AllChannels.from_dict(response)

        return res, 200
    except SQLAlchemyError as e:
        error = str(e.__dict__['orig'])
        return error


def get_channel_by_id(id):  # noqa: E501
    """Get a channel by its ID

    Returns a single Channel if it exists # noqa: E501

    :param id: The channel ID
    :type id: int

    :rtype: Channel
    """
    return 'do some magic!'


def update_channel_by_id(id, body=None):  # noqa: E501
    """Updates an existing channel

    Updates an existing channel # noqa: E501

    :param id: The channel ID
    :type id: int
    :param body: Channel to be added
    :type body: dict | bytes

    :rtype: None
    """
    if connexion.request.is_json:
        body = Channel.from_dict(connexion.request.get_json())  # noqa: E501
    return 'do some magic!'
