"""
server_controller.py

OpenAPI Generated Controller: Channel

This class is autogenerated by OpenAPI, for use with SQLAlchemy.
https://github.com/OpenAPITools/openapi-generator
"""
from swagger_server.models.server import Server


def search_server():  # noqa: E501
    """Returns information about the serverd

    Returns information about the server like the version its on and amount of users on the server  # noqa: E501


    :rtype: Server
    """
    return 'do some magic!'
